### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by slyons** [sabeegrewal/spark-eventhubs#11]
The current version of spark-eventhubs is only compatible with Java 1.8. On a hdinsight cluster deployed with Spark 1.6 the package "com.microsoft.azure:spark-streaming-eventhubs_2.10:1.6.0" is not compatible due to the version of Java used to compile.

**Comment by arijitt** [comment]
HDInsight supports 3 versions currently:

1. Spark 1.6.2 (HDI 3.4) – Supports Java 7/Scala 2.10 – this is still the default version.

Use spark-eventhubs JAR co-ordinates specified in the README at https://github.com/hdinsight/spark-eventhubs/tree/0.x (Github based private Maven repo)

2. Spark 1.6.2 (HDI 3.5) – Supports Java 8/Scala 2.10 – Use the drop down list

Use spark-eventhubs JAR co-ordinates specified in the README at https://github.com/hdinsight/spark-eventhubs/tree/1.x (Maven Central)

3. Spark 2.0.0 (HDI 3.5)  - Supports Java 8/Scala 2.11 – Use the drop down list (no Jupyter/Livy support yet)

Use spark-eventhubs JAR co-ordinates specified in the README at https://github.com/hdinsight/spark-eventhubs/tree/master (Maven Central)

**Comment by slyons** [comment]
For future reference it would probably be best to have semantic versioning that matches whatever is supported by the platform. As it stands the private Maven repo cannot be loaded by a HDI Jupyter notebook. If it were published such that V1 were for Java 7 / 1.6, V2 (or V1.1, etc) were for Java 8 / 1.6, and V2 was for Java 8 / 2.0 then it would follow established practices and would allow easier integration with future projects.

**Comment by arijitt** [comment]
We no longer support the private Maven repo. You should get the appropriate JARs from Maven Central where we will keep our code updated. The versioning is based on the Spark major version the eventhubs  receivers support.
