### ISSUE TITLE
Get offset from stream

### ISSUE THREAD

**Issue by jaminglam** [sabeegrewal/spark-eventhubs#4]
Hi All,

Is there any way to get the offset of partition from stream for self fault-tolerance implementation?

**Comment by perthcha** [comment]
I would like to know this too. Has anyone figured out?

**Comment by sabeegrewal** [comment]
Hey everyone, thanks for your interest in using Spark and EventHubs :) If this issue is still ongoing, please re-open a new issue! I'll be actively checking for issues, and would be happy to help out. Thanks!
